name: creek_alexa_plugin
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  creek_blue_manage:
    path: ../creekbluemanage

  #设备id获取
  device_info: ^2.0.2
  #网络请求
  dio: ^5.3.2
  #http2.0
  http2: ^2.2.0
  #录制音频
  flutter_sound: ^9.2.13
  audio_session: ^0.1.6
  #权限获取
  permission_handler: ^11.0.0
  #调用原生webview
  flutter_inappwebview: ^6.0.0-beta.25
  #本地数据存储
  shared_preferences: ^2.2.2
  #时间格式
  intl: ^0.18.1
  #获取随机uuid
  uuid: ^3.0.6
  #获取随机字符串
  crypto: ^3.0.3
  #压缩
  archive: ^3.4.3
  #网络链接状态
  connectivity_plus: ^5.0.1
  #音视频格式转换
  ffmpeg_kit_flutter: ^6.0.3
  #数据转模型
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1
  #时区获取
  flutter_native_timezone_updated_gradle: ^2.0.3
  #loading
  flutter_smart_dialog: ^4.9.5+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.5


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.creek.alexa.creek_alexa_plugin
        pluginClass: CreekAlexaPlugin
      ios:
        pluginClass: CreekAlexaPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
