name: creekbase
description: A new Flutter project.
version: 0.0.2
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  creektool:
    path: ../creektool

  plugin_platform_interface: ^2.1.6
#  flutter_easyloading: ^3.0.5
  flutter_smart_dialog: ^4.9.5+1
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  flustars_flutter3: ^3.0.0
  encrypt: ^5.0.3
  flutter_screenutil: ^5.9.0
  flutter_udid: ^2.0.1
  intl_utils: ^2.8.5
  localizely_sdk: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
flutter_intl:
  enabled: true
  localizely:
    project_id: 48a13802-d4cf-4af1-bc60-80683ffa2307







