name: creekchart
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6
  table_calendar: ^3.0.9
  dartx: ^1.2.0
  intl: ^0.18.1

  creekbase:
    path: ../creekbase

  fl_chart:
    path: ../fl_chart

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


