class SPUtilKey {
  static const String countryCode = 'country';
  static const String countryCodeLocal = 'countryCodeLocal';
  static const String languageCode = 'languageCode';
  static const String countryName = 'countryName';
  static const String mobileId = 'mobileId';
  static const String domainUrl = 'domainUrl';
  static const String accessToken = 'accessToken';
  static const String tokenExp = 'tokenExp';
  static const String refreshToken = 'refreshToken';
  static const String refreshTokenExp = 'refreshTokenExp';
  static const String forbidPopNotification = 'allowPopNotification';
  static const String checkUpdateTime = 'checkUpdateTime';
  static const String checkUpdateFrequency = 'checkUpdateFrequency';
  static const String synchEphemerisTime = 'synchEphemeris';
  static const String synchOffLineEphemerisTime = 'synchoffLineEphemeris';
  static const String synchoffLineEphemerisStartUtcTime = 'synchoffLineEphemerisStartUtcTime';
  static const String synchPhoneime = 'synchPhoneime';
  static const String newDialDic = 'newDialDic';
  static const String isParticipate='isParticipate';
  static const String isPrivacyPolicy='isPrivacyPolicy';
  static const String isShowDialogPrivacyPolicy='isShowDialogPrivacyPolicy';
  static const String upgradeReported='upgradeReported';
  static const String trackingCard ='trackingCard';
  static const String trackingZone ='trackingZone';
  static const String showNewVersion ="showNewVersion";
  static const String releaseService ="releaseService";
  static const String isSwitchEnvironments = "isSwitchEnvironments"; /// 是否切换过环境
  static const String isEmailVerification='isEmailVerification'; ///是否邮箱验证key
  static const String userName = "userName";
  static const String userPassword = "userPassword";
  static const String immediately = "immediately";///立即进入首页
  static const String isLogin = "isLogin"; ///是否登陆
  static const String tourist = "tourist"; ///游客登陆
  static const String isVerifyEmail = "isVerifyEmail"; ///是否验证邮箱
  static const String refreshTokenLastTime = "refreshTokenLastTime";
  static const String firstName = "firstName"; ///存储姓
  static const String privacyAgreeTime = "privacyAgreeTime"; ///协议时间
  static const String isPhotosKey = "isPhotosKey";
  static const String firstMenstrualPeriod = "firstMenstrualPeriod";
  static const String userId = 'userId'; ///存储用户ID
  static const String isOpenGoogleFit = 'GoogleFit'; ///是否开启谷歌健康
  static const String isOpenAppleHealth = 'AppleHealth'; ///是否开启苹果健康
  static const String updateAppInfoModel = 'updateAppInfoModel';
  static const String fireBaseToken = 'FireBaseToken';
  static const String lastHeartRateTime = 'LastHeartRateTime'; ///上次心率查询的时间
  static const String lastStepTime = 'LastStepTime'; ///上次步数查询时间查询的时间
  static const String appThemeKey = 'appThemeKey';
  static const String randomIndex = 'sleepRandomIndex'; ///睡眠小贴上index
  static const String isOpenLocation = 'isOpenLocations'; ///是否弹窗过定位
  static const String isNeedFlushUserInfo = "isNeedFlushUserInfo";
  static const String isShowGuide = "isShowGuide";
  static const String isShowCameraMessage = "isShowCameraMessage";
  static const String isShowLocationMessage = "isShowLocationMessage";
  static const String isShowPhotosMessage = "isShowPhotosMessage";
  static const String getTokenCustomerCode = "getTokenCustomerCode";
}
