name: creekbusiness
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  protobuf: ^3.1.0
  creek_blue_manage:
    path: ../creekbluemanage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

